[theme]
base = "dark"

[server]
enableXsrfProtection = true  # Sécurité recommandée
showAppSourceLink = false    # Cache le bouton "View app source"

[ui]
hideThemeSelector = true  # Empêche l'utilisateur de changer de thème